name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_SHEET_API_URL: https://script.google.com/macros/s/AKfycbz-fJITQQTy1SoSwf1NdNRXgVFNcnNU8OhO09xQtBbKZ3RSgYhvXcaGuQdjaQGwe4fI/exec
          VITE_NEWSLETTER_API_URL: https://script.google.com/macros/s/AKfycbwsXQAu04Qwy_dwK4-iHfD1FXolooBvOYXaQ0rJbBfEKhBfgMh_4V2WG3ko1Kh-Vwdk/exec
          VITE_CONTACT_API_URL: https://script.google.com/macros/s/AKfycbz-fJITQQTy1SoSwf1NdNRXgVFNcnNU8OhO09xQtBbKZ3RSgYhvXcaGuQdjaQGwe4fI/exec
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
